src/pages/index.js, src/styles/components/sectionUseCases.scss, src/styles/pages/index.scss, src/styles/templates/blog.scss
- hide GA track buttons in middle of some blogs
- update some UI
=> style: hide buttons snippet code

create-pages/blog.js, create-pages/blogs.js, create-pages/caseStudies.js, create-pages/position.js, create-pages/utils.js, src/components/blogHeader.js, src/components/blogs.js, src/components/positions.js, src/lib/string.js, src/pages/case-studies.js, src/pages/index.js, src/templates/blog.js, src/templates/blogCategories.js, src/templates/blogTags.js, src/templates/blogs.js, src/templates/caseStudy.js
=> Revert "Replace blog path preview"

gatsby-config.js, package.json, yarn.lock
=> chore: add sentry

.circleci/config.yml
=> chore: update beijing2 server

gatsby-config.js, package.json, yarn.lock
=> chore: add sitemap

src/components/pagination.js
All links to page 1 should be not have a page number. @std4453 Thanks for fixing this issue #73.
=> Fix incorrect pagination link (#73)

src/pages/download/community.js
=> chore: add two packages to community download page

create-pages/wrapPage.js, data/i18n/en.json, data/i18n/zh.json, gatsby-browser.js, gatsby-ssr.js, src/components/footer.js, src/components/navbar.js, src/data/footer.js, src/data/navbar.js
Use key-value-based solution for header and footer.
Some text are missing translation, this PR is only for a technical preview.
=> i18n for page layout components

markdown-pages/careers/product-marketing-manager-tidbcloud.md
=> add a new position

markdown-pages/careers/enterprise-sales-manager-apac.md
=> add a new position for enterprise sales manager, APAC

markdown-pages/careers/technical-support-manager.md
=> add a new position for technical support manager

markdown-pages/careers/software-engineer-cloud.md
=> add a new position for softer engineer, cloud

markdown-pages/careers/technical-support-engineer.md
=> updated technical support engineer

gatsby-config.js, package.json, yarn.lock
- use gatsby-plugin-rss to create an RSS feed for blogs
=> chore: add blog rss

src/components/blogs.js
=> Make blogs page banner image clickable

package.json, src/pages/index.js, yarn.lock
=> add throttle to scroll event listener on index page

src/components/blogHeader.js
=> Display multiple authors

src/styles/templates/blog.scss, src/templates/blog.js
=> image left-justified to center-justified

create-pages/caseStudies.js, src/pages/case-studies.js
injected language context in createPage of case studies manually
=> case studies i18n

gatsby-browser.js, gatsby-config.js, package.json, yarn.lock
=> Link anchor issues

src/styles/templates/blog.scss
=> Center justify Tables

src/components/layout.js, src/pages/zh/404.js
- hide cookie consent on Chinese pages
- add 404 page for non-exist Chinese pages
=> update cookie consent

src/styles/templates/blog.scss
* fix: fixed tab style on blog page
* fix: fixed missing part and error
=> fix tab style on blog page (#168)

gatsby-config.js
exclude all pages `/zh/any_path/to/page/`
=> fix: update sitemap to match any number of characters

create-pages/blog.js, create-pages/caseStudies.js, create-pages/position-zh.js, gatsby-node.js
Generate aliases page for pages which changed file names
=> chore: generate aliases pages

src/components/seo.js
Closes #126 
See comments in the issue.
=> Social media cards

src/pages/products/tidbcloud/index.js, src/styles/pages/products/tidbCloud.scss
https://github.com/pingcap/website/issues/203
=> chore: replace an image with a video

src/components/layout.js, src/components/navbar.js, src/data/footer.js, src/data/zh/contact-us-form.js, src/pages/zh/about.js, src/pages/zh/contact-us.js, src/pages/zh/index.js, src/styles/pages/contactUs.scss, src/styles/pages/zh/user-message-2019.scss
Fixed bugs mentioned in https://docs.google.com/document/d/158fTNjBoTdQlchTUABPy_h8B0_WmbW19WycZB_eY3es/edit
=> Fix bugs mentioned in feedback document

gatsby-config.js
- Generate sitemap for different languages. Add a child element `<xhtml:link rel="alternate" hreflang="supported_language-code">` to each url to tell Google about language and region variations. [See more details](https://support.google.com/webmasters/answer/189077?hl=en).
- Most web-viewers are not able to pretty print the sitemap `/sitemap-${lang}.xml`, however, the sitemap is still a valid sitemap. You can also view source page to check the validation. [See more details](https://github.com/gatsbyjs/gatsby/issues/5888).
- Add all `/sitemap-${lang}.xml` to `/sitemap.xml`.
=> chore: update sitemap

markdown-pages/careers/technical-support-engineer.md
please add a base in technical support engineer, PTAL  @YiniXu9506
=> add a base in Technical support engineer

markdown-pages/careers/dba.md
add a new job, PTAL~ @YiniXu9506
=> add a new dba position

create-pages/blogCNPages.js, gatsby-node.js, src/components/blogs.js, src/pages/blog-cn.js
- redirect `/blog-cn/#tag` to `/zh/blog/tag/#tag`
- redirect `/blog-cn/BLOG_PATH` to `/zh/blog/BLOG_PATH`
=> chore: redirect /blog-cn/* to corresponding page under /zh/blog/

markdown-pages/download-blogs.js, markdown-pages/utils.js, src/components/shortcodes/index.js, src/components/shortcodes/trackGABtns.js, src/styles/components/trackGABtns.scss, src/styles/templates/blog.scss
- replace GA track button stream
- add shortCode for GA  track button
=> chore: replace GA trackable buttons

markdown-pages/terms/cookie-policy.md, markdown-pages/terms/privacy-policy.md
- Fix and update format
- Fix Chinese punctuation
- Fix typos: Agolia > Algolia
- Make word consistent: pseudonymise > pseudonymize
@YiniXu9506 @dcalvin PTAL
=> terms: fix format and typos in privacy policy and cookie policy

src/data/navbar.js, src/pages/products/tidbcloud/index.js
1. Updated homepage banner
2. Updated video on the  TiDB Cloud page
=> update banner and video

create-pages/allCaseStudies.js, create-pages/blogCategories.js, create-pages/caseStudies.js, create-pages/caseStudyCategories.js, gatsby-node.js, src/components/blogHeader.js, src/components/blogs.js, src/components/labels.js, src/components/menu.js, src/lib/dataType.js, src/lib/graphql/blog.js, src/lib/menuCfgGenerator.js, src/lib/proxy.js, src/styles/templates/blog.scss, src/templates/caseStudy.js, src/templates/caseStudyCategory/all.js, src/templates/caseStudyCategory/company.js, src/templates/caseStudyCategory/industry.js, src/templates/caseStudyCategory/tags.js
- create case studies category pages
- refactor componnets/blogs for adding tags on case studies category
=> Add tags on case studies category

src/components/labels.js, src/lib/menuCfgGenerator.js, src/pages/case-studies.js, src/templates/caseStudy.js
- fixed tags link on zh case study detail
- fixed category name on case study
=> Fixed tag link and category name

.circleci/config.yml
=> chore: prevent css/js/images folders from deleting on destination server

src/components/footer.js, src/styles/components/footer.scss
- Move PingCAP logo to the right-bottom
- Adjust language switcher position
=> chore: update footer layout

data/zh/news.json, src/data/footer.js, src/pages/zh/news.js
=> chore: add Chinese news

src/pages/download/index.js, src/pages/products/tidb.js
This PR includes two changes:
1. Update the contributor number on TiDB page
2. Add Slack invite info on the download page
=> update contributor number and Slack info on download page

data/news.json
=> Add libbpf-tools  and AWS news

src/pages/products/tidbcloud/index.js
=> chore: hide the memory col, remove disk_type info in the storage col

data/news.json
@ran-huang FYI.
@YiniXu9506 PTAL
=> Add cross-AZ article on DZone

data/news.json
@huang-ran FYI.
@YiniXu9506 PTAL
=> Add TiDB Operator Source Code Reading (Part 1)

gatsby-config.js, package.json, yarn.lock
Tracking users behavior with LinkedIn avatar.
=> chore: add tracking code for LinkedIn Insight Tag

gatsby-config.js
=> chore: add Google Tag Manager

data/news.json
=> add spdk in the news

data/news.json
=> data: add 4 posts to news

data/i18n/en.json, src/data/navbar.js
=> Revert "Update the CTA button"

data/news.json
=> add 1 post in the news

data/news.json
=> add ttl in the news

gatsby-config.js, package.json, yarn.lock
=> Revert "chore: add hotjar plugin"

data/news.json
=> add 4 news

src/pages/products/tidbcloud/index.js, src/styles/_variables.scss, src/styles/pages/products/tidbCloud.scss
=> feat: add dev tier introduction

data/i18n/en.json, data/i18n/jp.json, src/components/pricing.js, src/pages/jp/products/tidbcloud/index.js
=> feat: add dev tier to jp
